### ISSUE TITLE
standard_newton_power_series crashes Sage

### ISSUE THREAD

**Issue by nbliss** [janverschelde/PHCpack#21]
Running the following example in Sage:

`from phcpy.series import standard_newton_power_series as standardNewt`
`pols = ['6.0*t + x^2 + 3.0*y^2 - r^2 + (-2.0)*r - 1.0;',\                        `
 `       'x^2 + 3.0*y^2 - r^2 + (-4.0)*x + (-2.0)*r + 3.0;',\                     `
  `      '3.0*t^2 + x^2 + (-6.0)*t*y + 3.0*y^2 - r^2 + (-2.0)*x + (-6.0)*y + 2.0*r + 3.0;']`
`sols = ['t;', '1.0;', '7.46410161513776*t + 1.0;', '11.1961524227066*t + 1.0;']  `
`print newt(pols, sols)`

causes Sage to crash with the following error message:
0   signals.so                          0x000000010c217f85 print_backtrace + 37
Unhandled SIGSEGV: A segmentation fault occurred.
This probably occurred because a *compiled* module has a bug
in it and is not properly wrapped with sig_on(), sig_off().
Python will now terminate.
/Applications/SageMath/src/bin/sage-python: line 2: 36130 Segmentation fault: 11  sage -python "$@"

I'm running SageMath version 8.0, Release Date: 2017-07-21, and PHCv2.4.48 released 2017-12-30. Using dobldobl_newton_power_series crashes Sage as well. The quad double version seems to succeed, although the coefficients are pretty huge, so I'm wondering if it's just some kind of overflow error. Either way, these functions are crashing Sage even with the cysignals fix in place.

**Comment by janverschelde** [comment]
The problem with the input is the first entry in sols which should not be there, it should be
sols = ['1.0;', '7.46410161513776*t + 1.0;', '11.1961524227066*t + 1.0;']
The new version of the code has a check on the input which will tell the user if the length
of the leading terms is not right.  The new version has been installed in the Sage kernel
on http://www.phcpack.org.

**Comment by nbliss** [comment]
Ah that makes sense. Thanks!
