### ISSUE TITLE
phcpy export homotopy

### ISSUE THREAD

**Issue by zhangyusi-hub** [janverschelde/PHCpack#31]
How can I use phcpy to export the homotopy H(x, t) to find whether it is h(x, t) = γ(1 − t)g(x) + t f(x)  or not?

**Comment by janverschelde** [comment]
Could you make your question more precise?   With an example perhaps?

**Comment by zhangyusi-hub** [comment]
If I want to use phcpy to solve the polynomial system f = ['x^2*y^2 + x + 1;', 'x^2*y^2 + y + 1;'],where I use the total degree to get a start polynomial g = ['x^4 - 1;', 'y^4 - 1;'] and with a finite γ. 
How  to  use phcpy to export the homotopy H(x, t) = γ(1 − t)g(x) + t f(x) = [' γ*(1-t)*(x^4 - 1) + t*(x^2*y^2 + x + 1);', 'γ*(1-t)*(y^4 - 1) + t*(x^2*y^2 + y + 1);']?

**Comment by janverschelde** [comment]
To solve a system with a total degree start system in phcpy, do the following:

from phcpy.solver import total_degree_start_system
from phcpy.trackers import track

f = ['x^2*y^2 + x + 1;', 'x^2*y^2 + y + 1;']
g, gsols = total_degree_start_system(f)
for pol in g:
    print(pol)
for sol in gsols:
    print(sol)
fsols = track(f,g,gsols)
for sol in fsols:
    print(sol)

**Comment by zhangyusi-hub** [comment]
To solve a system with a total degree start system in phcpy, Can I use phcpy to export the homotopy H ? 
For example, export f I can know f = ['x^2y^2 + x + 1;', 'x^2y^2 + y + 1;'], and how to export H to vertify that H = γ*(1-t)*g + t * f rather than H = γ*(1-t)^2*g + t ^2 * f?

**Comment by janverschelde** [comment]
The trackers module of phcpy implements an aposteriori step size control and the functions to launch the trackers allow to pass a specific value for gamma.  The power of t in the homotopy is there by default 2 and cannot be passed.  I may be able to fix this in a future release, so the user can set the power of t and (1-t) when calling the track functions.
The curves module of phcpy implements an apriori step size control.  The power of t and (1-t) is 2 with affine coordinates and 1 in projective coordinates, but this cannot be changed by the phcpy user.  I may also be able to fix this in a future release of phcpy.  Thanks for raising this issue.

**Comment by zhangyusi-hub** [comment]
Thank you for your last answer! I have another problem, when I do the following:

from phcpy.solver import total_degree_start_system
from phcpy.trackers import initialize_standard_tracker
from phcpy.trackers import initialize_standard_solution
from phcpy.trackers import next_standard_solution
from phcpy.solutions import strsol2dict
p = ['x**2 + 4*x**2 - 4;', '2*y**2 - x;']
(q, s) = total_degree_start_system(p)
s1 = s[1]
s2 = s[3]
initialize_standard_tracker(p, q)
initialize_standard_solution(len(p), s1)
points = [next_standard_solution() for i in range(11)]
dicpts = [strsol2dict(sol) for sol in points]
tvals = [sol['t'] for sol in dicpts]
print(tvals)
that is [(0.1+0j), (0.2+0j), (0.3+0j), (0.4+0j), (0.5+0j), (0.6+0j), (0.7+0j), (0.8+0j), (0.9+0j), (1+0j), (1+0j)].

initialize_standard_tracker(p, q)
initialize_standard_solution(len(p), s2)
points = [next_standard_solution() for i in range(11)]
dicpts = [strsol2dict(sol) for sol in points]
tvals = [sol['t'] for sol in dicpts]
print(tvals)
that is [(0.1+0j), (0.2+0j), (0.3+0j), (0.4+0j), (0.5+0j), (0.6+0j), (0.7+0j), (0.7+0j), (0.77+0j), (0.84+0j), (0.9275+0j)].
why does the two tvals are different? And I want to know t how to change for 0 to 1.

**Comment by zhangyusi-hub** [comment]
> To solve a system with a total degree start system in phcpy, Can I use phcpy to export the homotopy H ?
> For example, export f I can know f = ['x^2y^2 + x + 1;', 'x^2y^2 + y + 1;'], and how to export H to verify that H = γ * (1-t) * g + t * f rather than H = γ * (1-t)^2 * g + t ^2 * f?

**Comment by janverschelde** [comment]
The t values are different because with
points = [next_standard_solution() for i in range(11)]
the first ten points computed on the path are request.
If you want to reach 1, more than 10 steps are needed.

**Comment by zhangyusi-hub** [comment]
Could you tell me how to change the t values with the function next_standard_solution()? For example, the current t values is 0.7+0j, and after running the function next_standard_solution(), the t value is 0.77+0j rather than 0.8+0j?
