### ISSUE TITLE
"bablroco.ads" not found is shown while compiling

### ISSUE THREAD

**Issue by YHHuang87** [janverschelde/PHCpack#34]
Hello, I'm a newphyte who is currently testing phcpack performance on the GPU of our lab. I was trying to compile your file in the terminal by following the instruction written in documentation. However, when I typed "make" in the "Object" directory, the following error message occurred:

`Compiling: /home/b06096/PHCpack-master/src/Ada/Main/option_handlers.adb
Source file time stamp: 2020-12-08 04:13:03
Compiled at: 2020-12-08 14:21:32

    15. with bablroco;
             |
        >>> file "bablroco.ads" not found

 867 lines: 1 error
gnatmake: "/home/b06096/PHCpack-master/src/Ada/Main/option_handlers.adb" compilation error
makefile_unix:100: recipe for target 'phc' failed
make[1]: *** [phc] Error 4
make[1]: Leaving directory '/home/b06096/PHCpack-master/src/Objects'
makefile:15: recipe for target 'phc' failed
make: *** [phc] Error 2
`
I've checked that I've downloaded every file in your repository and every file is indeed downloaded. Therefore, I'm not so sure about the reason for this error message. Could you address my problem? It will be extremely beneficial to me. Thanks.

**Comment by janverschelde** [comment]
That is odd.  This 'bablroco' was removed on 21 November and the option_handlers.adb have been updated.
How did you download the source code?  If you cloned the repository with git, then a pull should update.
If you are not a git user, then you could download the last tag, version 2.4.82.

**Comment by YHHuang87** [comment]
Thank you for responding. However, I've encountered other problems while compiling. I will close this issue with this comment.
