### ISSUE TITLE
issue of making the shared object file for python2 or python3

### ISSUE THREAD

**Issue by C-H-Chien** [janverschelde/PHCpack#39]
I encountered an error when I was trying to make the shared object file for either python2 or python3.
Here's what I met when I type `make phcpy2c3.so` or `make phcpy2c2.so`

/usr/bin/ld: phcpy2c3.a(black_polyhedral_continuations.o): relocation R_X86_64_PC32 against symbol `continuation_parameters__start_end_game' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[1]: *** [makefile_unix:4074: phcpy2c3.so] Error 1
make[1]: Leaving directory '/home/chchien/BrownU/research/PHCPACK/PHCv2_4p/Objects'
make: *** [makefile:34: phcpy2c3.so] Error 2

It seems that I need to recompile the qd library with -fPIC, but when I did it, the above error still occurs.

I build and compile the qd from [here](https://github.com/scibuilder/QD), and the outcome after compilation shows:

Using 
  C++ Compiler      = /usr/bin/g++
  C++ Flags         = -fPIC -O3  -DHAVE_CONFIG_H
  F90 Compiler      = f95
  F90 Flags         = -O2 -ffree-form  
  F90 Libs          =  -L/usr/lib/gcc/x86_64-linux-gnu/9 -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/9/../../.. -lgfortran -lm -lquadmath 
  enable fortran    = yes
  enable inline     = yes
  enable x86 fix    = yes
  enable ieee add   = no
  enable sloppy mul = yes
  enable sloppy div = yes
  fma               = none
  fms               = none

Am I compiling correctly? If so, what should I do or check with the `make phcpy2c2.so` error?
Thanks in advance!!

**Comment by janverschelde** [comment]
The shared object files are compiled with the GNAT Community edition,
available at https://www.adacore.com/community
and the folder with the binaries of the gnu-ada compiler should be placed in front of the path.
Also it is best to compile the QD library with the gnu-ada compiler, F90 is not needed.

**Comment by C-H-Chien** [comment]
Hi, thanks for the feedback and I am sorry for the late reply.

I did use GNAT file to compile and the binaries of the gnu-ada compiler was placed in front of the path.
The problem of making the shared object file still exists. The error messages showed that there are multiple re-definitions of 'main', so I traced back to the file where the main function appears multiple times. This comes to file with file names begin with `ts_` (test files?) in the `Feedback` folder. I somehow removed those files and forcefully added the remaining files with file names not begin with `ts_` in the `makefile_unix`:

# files in feedback :

lib.a:$(PHCAda)/../Feedback/append_dcmatrix.c /../Feedback/append_polymatrix.c /../Feedback/c2ada_dc_matrix.c /../Feedback/c2ada_poly_matrix.c /../Feedback/dc_interpolation.c /../Feedback/dc_inverse.c /../Feedback/dc_matrix.c /../Feedback/dcmplx.c /../Feedback/dc_roots.c /../Feedback/feedback.c /../Feedback/pieri_sols.c /../Feedback/poly_dcmplx.c /../Feedback/poly_gcd.c /../Feedback/poly_hermite.c /../Feedback/poly_matrix.c /../Feedback/poly_smith.c /../Feedback/read_input.c /../Feedback/realization.c /../Feedback/timer.c $(PHCAda)/../Feedback/*.h
	gcc -c $(PHCAda)/../Feedback/*.c
	ar ruv lib.a    dc_interpolation.o  dcmplx.o       poly_matrix.o\
       append_dcmatrix.o    dc_inverse.o        pieri_sols.o   poly_smith.o\
       c2ada_dc_matrix.o    dc_matrix.o         poly_dcmplx.o  realization.o\
       c2ada_poly_matrix.o  dc_roots.o          poly_gcd.o     ts_feedback.o\
       poly_hermite.o       append_polymatrix.o timer.o
	ranlib lib.a 

After that, make phc and phcpy again and it works!
