### ISSUE TITLE
Multiple issues when intersecting witness sets

### ISSUE THREAD

**Issue by wilrop** [janverschelde/PHCpack#60]
## Context
I have two systems of polynomial equations which are underdetermined. In my use case, I want to solve the systems individually first, so I calculate their witness sets. Later, I want to find the joint solutions to the two systems combined without having to completely resolve the combined system. Rather, I take the intersection of the witness sets by using `diagonal_solver` as suggested in the docs [here](http://homepages.math.uic.edu/~jan/phcpy_doc_html/posdimsols.html). 

## Issue
The problem is that it results in very frequent memory errors. Consider the minimal example below. 

```python
from phcpy.solver import solve
from phcpy.sets import embed
from phcpy.diagonal import diagonal_solver as diagsolve

pols1 = ['(4*c*f + 2*c*g + 1*d*f + 6*d*g) - (6*c*f + 1*c*g + 2*d*f + 4*d*g) + a - a + b - b;', 'c + d - 1;', 'f + g - 1;']
pols2 = ['(2*a*f + 3*a*g + 4*b*f + 5*c*g) - (3*a*f + 5*a*g + 2*b*f + 4*c*g) + c - c + d - d;', 'a + b - 1;', 'f + g - 1;']

nvar = 6
dim1 = 3
dim2 = 3

emb1 = embed(nvar, dim1, pols1, precision='d')
emb2 = embed(nvar, dim2, pols2, precision='d')

sols1 = solve(emb1, verbose=False, precision='d')
sols2 = solve(emb2, verbose=False, precision='d')

res = diagsolve(nvar, dim1, emb1, sols1, dim1, emb2, sols2, verbose=False, prc='d')
pols, points = res

for point in points:
    print("---")
    print(point)
```

and the exception:

```
Exception raised in Store_Start_System
The system p is 
( 2.31394490318442E-01 + 8.94811216632679E-02*i)+(-3.02693632988134E+00 + 8.38280512867671E-01*i);
( 1.64130605527301E+00 + 4.55548682918410E-02*i)+( 1.15874496014289E+00 - 7.71065567280865E-02*i);
(-8.19257066903764E-01 - 3.81692925701712E-01*i)*g}|j||dd|d�|j||ddd�|j|d|dd	d
+( 1.34232598168258E+00 - 3.18067046900866E-01*i);
(-9.07970433094135E-01 + 1.30008728707763E+00*i);

raised CONSTRAINT_ERROR : erroneous memory access
```
Note that the ``Exception raised in Store_Start_System`` is not always printed, which leads me to believe the problem can occur in multiple places. In addition, for smaller systems, it can sometimes give an output and sometimes crash. 

My guess is that there is a memory issue because the intersection is taking too much from the stack. I looked up this problem, and there is a solution proposed [here](https://stackoverflow.com/questions/22571892/large-arrays-raises-erroneous-memory-access-ada). Unfortunately, I have no ada experience so I don't feel confident in trying to tackle this myself. If you don't have time to solve this issue but do have an idea of specifically which function this problem could be at, I will attempt to solve it myself.

If I can help further with these problems, please let me know. I'm relying quite heavily on PHCpack for my current work so I would like to help as best as I can!

**Comment by janverschelde** [comment]
Thanks for reporting this issue.  I will try to get to this soon.

**Comment by wilrop** [comment]
I have found a much smaller example that also raises errors. I believe that means we can rule out the hypothesis that there only is a simple memory issue where some systems simply take too much space.

```python
polys1 = ['p0_0 - 1;', 'p1_0 + p1_1 - 1;', 'p0_1;']
polys2 = ['p0_0 + p0_1 - 1;', 'p1_0 - 1;', 'p1_1;']

emb1 = embed(4, 1, polys1)
emb2 = embed(4, 1, polys2)
sols1 = solve(emb1, verbose=False)
sols2 = solve(emb2, verbose=False)

polys, sols = diagsolve(4, 1, emb1, sols1, 1, emb2, sols2, verbose=False)
```
The first polynomial system has 1 as top dimension, as ``p0_0`` and ``p0_1`` are already determined. The same goes for polynomial system 2 with ``p1_0`` and ``p1_1``. The output and error are as follows:
```
PHCv2.4.85 released 2021-06-30 works!
number of symbols : 5
names of variables : p0_0 zz1 p1_0 p1_1 p0_1

raised CONSTRAINT_ERROR : erroneous memory access
```

Note that the intersection exists and should be:
```
p0_0 = 1
p0_1 = 0
p1_0 = 1
p1_1 = 0
```

**Comment by janverschelde** [comment]
Thank you very much for this great example.
This example can be solved with the command line versions of phc (via the option -c).  So it is an interface issue.
I will have time soon to resolve this.

**Comment by janverschelde** [comment]
The interface code for the embed function added duplicate embed symbols and that is fixed.

Another problem is that for the diagonal solver to work, the symbols in the two systems must appear in the same order.
The hack to achieve this same order is to insert a polynomial that evaluates to zero to the first polynomial.
For example, for your last example, do

varequ = 'p0_0 + p0_1 + p1_0 + p1_1 - p0_0 - p0_1 - p1_0 - p1_1'
emb1 = embed(4, 1, polys1)
emb1[0] = varequ + ' + ' + emb1[0]
emb2 = embed(4, 1, polys2)
emb2[0] = varequ + ' + ' + emb2[0]

With the bug fix and the hack to order to variables, the diagonal solver now works on that example.
I still have to look at the other examples.

**Comment by janverschelde** [comment]
After fixing the output of negative integer coefficients, the first example in this issue should work as well,
with the insertion of the zero polynomial a + b + c + d + f + g - a - b - c - d - f - g to the first polynomial
of the two embedded systems, to obtain the same order of the variables in both systems.

**Comment by wilrop** [comment]
I have verified that both examples are indeed fixed. A big thanks for solving the problems, I greatly appreciate it! You can close the issue if you like.
