### ISSUE TITLE
clang: error: unknown argument

### ISSUE THREAD

**Issue by user074** [janverschelde/PHCpack#63]
Hey. I am compiling binary on macOS 12.4.
I have installed x86 Mac OS X (64 bits) GNAT (2020 version), but I am encountering issue with clang while make phc
Following are what errors I got:
`clang: error: unknown argument: '-gnatA' `
`clang: error: unknown argument: '-gnatWb'`
`clang: error: unknown argument: '-gnatiw'`
`clang: error: unknown argument: '-gnatws'`

I wonder how to resolve this issue. Thank you very much

**Comment by janverschelde** [comment]
The error message comes from clang not from gnatmake.  When you install GNAT, please adjust the path so gcc is called instead of clang.
