### ISSUE TITLE
Downloading the binary

### ISSUE THREAD

**Issue by RagonEbker** [janverschelde/PHCpack#67]
Hello,
I am trying to download the binaries from http://homepages.math.uic.edu/~jan/download.html, but it gives me a 404. Does anyone know if there is a mirror or if its possible to reupload the file?

Greetings 
Ragon

**Comment by janverschelde** [comment]
Thanks for your interest in PHCpack.
The binaries are posted as the assets of version 2.4.85
https://github.com/janverschelde/PHCpack/releases/tag/v2.4.85
________________________________
From: RagonEbker ***@***.***>
Sent: Friday, August 4, 2023 6:06 PM
To: janverschelde/PHCpack ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [janverschelde/PHCpack] Downloading the binary (Issue #67)


Hello,
I am trying to download the binaries from http://homepages.math.uic.edu/~jan/download.html, but it gives me a 404. Does anyone know if there is a mirror or if its possible to reupload the file?

Greetings
Ragon

**Comment by RagonEbker** [comment]
Hello Jan,
wow! Thank you for your fast help! When executing the phc file I encounter an error:
`./phc: 1: ./phc: Syntax error: ")" unexpected`
this happens with the command `sudo ./phc`

Before that I tried executing with `./phc` and it gave me the error `bash: ./phc: cannot execute binary file: Exec format error
`, even though the file has permission to be exectued.
