### ISSUE TITLE
Scalesys throws exception

### ISSUE THREAD

**Issue by hsidky** [janverschelde/PHCpack#7]
Hello again, 

I been using PHCPy and ran into an issue where an admittedly nasty polynomial is causing `scalesys` to throw an exception. I first compute the multihomogeneous Bezout bound on my polynomial without trouble, then I attempt to scale it. This causes PHCPy to output the following:

`Exception raised in use_c2phc handling job 67.  Will not ignore.
Ignoring the exception, returning job number.`

It appears to still return a scaled system with coefficients, but I am concerned about the result. If it matters any, my system is in 6 variables and has a MBZ of 1792. 

**Edit:** Upon closer inspection, it appears that equations 5 is truncated. Equations 1-4,6 appear to be fine. Equation 5 is the most "complicated" of the bunch.

Thanks.

**Comment by janverschelde** [comment]
Thanks for reporting this bug.  I suspect that the origin for the bug is that I have set fixed
limits on the size of the string representations of the polynomials.
Could you make your equations available (either via personal email to me or a posting)
so I could test the fix of the bug?

**Comment by hsidky** [comment]
I have put my system here: http://pastebin.com/MmYFBskN set to expire in an hour. If you don't manage to get it before then, I will re-post it. Thanks again!

**Comment by janverschelde** [comment]
Thanks for the system.  The latest commits provide a patch.
For the next release 2.4.01, I hope to provide a more durable solution to this bug.

**Comment by hsidky** [comment]
Thank you very much for putting up a fix so quickly. I look forward to the next release; I expect the the size of my system to grow.
