### ISSUE TITLE
Does there exists a package for the users of Windows system?

### ISSUE THREAD

**Issue by Xinli-zjut** [janverschelde/PHCpack#70]
Dear Professor, we wonder if there exists a version of PHCpack for the users of WIndows  operating system. In your help manual, you said:  "For the Windows operating systems, the executable version of phc is in the file phc.exe and is available for download in its uncompressed format."

**Comment by janverschelde** [comment]
Thanks for your interest in PHCpack.
Executable versions of the program can be found
under the assets of the releases:
https://github.com/janverschelde/PHCpack/releases/tag/v2.4.88
[https://opengraph.githubassets.com/c602dcdd6546519421ca5d19f7897e5cb86f31201d00c92fb845a8964785d53a/janverschelde/PHCpack/releases/tag/v2.4.88]<https://github.com/janverschelde/PHCpack/releases/tag/v2.4.88>
Release v2.4.88 · janverschelde/PHCpack<https://github.com/janverschelde/PHCpack/releases/tag/v2.4.88>
Fixed a bug in the blackbox solver in double double and quad double precision when deflation was applied. Provided an alire workspace to build the code better, at least on Windows. Extended the ser...
github.com

________________________________
From: Xinli-zjut ***@***.***>
Sent: Tuesday, January 9, 2024 4:21 AM
To: janverschelde/PHCpack ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [janverschelde/PHCpack] Does there exists a package for the users of Windows system? (Issue #70)


Dear Professor, we wonder if there exists a version of PHCpack for the users of WIndows operating system. In your help manual, you said: _"For the Windows operating systems, the executable version of phc is in the file phc.exe and is available for download in its uncompressed format."

**Comment by Xinli-zjut** [comment]
Dear professor, we are grateful to your generous  sharing.
